CREATE TABLE BANK_ACCOUNTS(
    ID BIGINT NOT NULL,
    BIC VARCHAR(255),
    IBAN VARCHAR(255),
    SWIFT VARCHAR(255),
    USER_ID BIGINT
);              
ALTER TABLE BANK_ACCOUNTS ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BANK_ACCOUNTS;           
CREATE TABLE CREDIT_CARDS(
    ID BIGINT NOT NULL,
    EXPIRATION_DATE VARCHAR(255),
    NUMBER VARCHAR(255),
    SECRET_CODE VARCHAR(255),
    USER_ID BIGINT
);           
ALTER TABLE CREDIT_CARDS ADD CONSTRAINT CONSTRAINT_8 PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CREDIT_CARDS;            
CREATE TABLE FRIENDS(
    PERSON_ID BIGINT NOT NULL,
    FRIEND_ID BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.FRIENDS; 
CREATE TABLE TOP_UPS(
    ID BIGINT NOT NULL,
    DATE TIMESTAMP,
    SUM DOUBLE NOT NULL,
    CARD_ID BIGINT,
    USER_ID BIGINT
);        
ALTER TABLE TOP_UPS ADD CONSTRAINT CONSTRAINT_E PRIMARY KEY(ID);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TOP_UPS; 
CREATE TABLE TRANSACTIONS(
    ID BIGINT NOT NULL,
    AMOUNT VARCHAR(255),
    CONNECTION VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    USER_ID BIGINT
);
ALTER TABLE TRANSACTIONS ADD CONSTRAINT CONSTRAINT_F PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TRANSACTIONS;            
CREATE TABLE TRANSFERS(
    ID BIGINT NOT NULL,
    COMMISSION DOUBLE NOT NULL,
    DATE TIMESTAMP,
    DESCRIPTION VARCHAR(255),
    SUM DOUBLE NOT NULL,
    RECEIVER_ID BIGINT,
    SENDER_ID BIGINT
);            
ALTER TABLE TRANSFERS ADD CONSTRAINT CONSTRAINT_E4 PRIMARY KEY(ID);   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TRANSFERS;               
CREATE TABLE USERS(
    ID BIGINT NOT NULL,
    BALANCE DOUBLE,
    EMAIL VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    PASSWORD VARCHAR(255)
);            
ALTER TABLE USERS ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY(ID);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
CREATE TABLE WITH_DRAWS(
    ID BIGINT NOT NULL,
    DATE TIMESTAMP,
    SUM DOUBLE NOT NULL,
    BANK_ID BIGINT,
    USER_ID BIGINT
);     
ALTER TABLE WITH_DRAWS ADD CONSTRAINT CONSTRAINT_E9 PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.WITH_DRAWS;              
ALTER TABLE TOP_UPS ADD CONSTRAINT FK1UUHPA1143DO5YB17QNQ9MKD9 FOREIGN KEY(USER_ID) REFERENCES USERS(ID) NOCHECK;        
ALTER TABLE FRIENDS ADD CONSTRAINT FKHHJKSYQJGVP1R88YV1PREWT3O FOREIGN KEY(PERSON_ID) REFERENCES USERS(ID) NOCHECK;      
ALTER TABLE BANK_ACCOUNTS ADD CONSTRAINT FKAHRJ5M84HFC167GPMA9VCWE0J FOREIGN KEY(USER_ID) REFERENCES USERS(ID) NOCHECK;  
ALTER TABLE CREDIT_CARDS ADD CONSTRAINT FKN1THFI0PEV97G7G4OREO6G4YW FOREIGN KEY(USER_ID) REFERENCES USERS(ID) NOCHECK;   
ALTER TABLE TRANSFERS ADD CONSTRAINT FKINWE0246UYU4691M6T4RR3QAV FOREIGN KEY(RECEIVER_ID) REFERENCES USERS(ID) NOCHECK;  
ALTER TABLE TRANSFERS ADD CONSTRAINT FKPN4X20JHIOY57YKP4BE3JNEI4 FOREIGN KEY(SENDER_ID) REFERENCES USERS(ID) NOCHECK;    
ALTER TABLE TOP_UPS ADD CONSTRAINT FKKSF94TJVO4NTOVXN9IJNPGOXG FOREIGN KEY(CARD_ID) REFERENCES CREDIT_CARDS(ID) NOCHECK; 
ALTER TABLE WITH_DRAWS ADD CONSTRAINT FKTFRTEAGE0N1RS513TX6B6P0I2 FOREIGN KEY(USER_ID) REFERENCES USERS(ID) NOCHECK;     
ALTER TABLE FRIENDS ADD CONSTRAINT FKC42EIHJTIRYERIY8AXLKPEJO7 FOREIGN KEY(FRIEND_ID) REFERENCES USERS(ID) NOCHECK;      
ALTER TABLE TRANSACTIONS ADD CONSTRAINT FKQWV7RMVC8VA8REP7PIIKROJDS FOREIGN KEY(USER_ID) REFERENCES USERS(ID) NOCHECK;   
ALTER TABLE WITH_DRAWS ADD CONSTRAINT FKSQ7F25ETYCNN8UAQUXW8DGX74 FOREIGN KEY(BANK_ID) REFERENCES BANK_ACCOUNTS(ID) NOCHECK;             
